name: google_mobile_ads_ironsrc
description: A new Flutter project.
version: 2.4.0
publish_to: 'none'

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.androidhuman.plugins.google_mobile_ads_ironsrc
        pluginClass: GoogleMobileAdsIronsrcPlugin
      ios:
        pluginClass: GoogleMobileAdsIronsrcPlugin
